// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package inputs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "maps"

type ButtonOptions struct {
	Text     string
	Varient  string
	Disabled bool
	Htmx     HtmxOptions
}

type HtmxOptions struct {
	HxGet     *string
	HxTarget  *string
	HxSwap    *string
	HxPushUrl *string
}

func (b *ButtonOptions) TemplAttributes() templ.Attributes {
	tmplAttr := templ.Attributes{}
	if b.Disabled {
		tmplAttr["disabled"] = b.Disabled
	}

	btnClasses := " uppercase font-bold py-2 px-4 rounded my-2 w-full disabled:bg-stone-400 disabled:text-white"
	switch b.Varient {
	case "contained":
		tmplAttr["class"] = "bg-varient-primary hover:bg-varient-primary-hover text-white" + btnClasses
	case "text":
		tmplAttr["class"] = "bg-transparent text-varient-primary hover:border hover:border-varient-primary" + btnClasses
	case "outline":
		tmplAttr["class"] = "bg-transparent text-varient-primary border border-varient-primary" + btnClasses
	default:
		tmplAttr["class"] = "bg-varient-primary hover:bg-varient-primary-hover text-white" + btnClasses
	}

	htmxAttr := b.Htmx.TemplAttributes()

	maps.Copy(tmplAttr, htmxAttr)

	return tmplAttr
}

func (h *HtmxOptions) TemplAttributes() templ.Attributes {
	tmplAttr := templ.Attributes{}
	if h.HxGet != nil {
		tmplAttr["hx-get"] = h.HxGet
	}
	if h.HxTarget != nil {
		tmplAttr["hx-target"] = h.HxTarget
	}
	if h.HxSwap != nil {
		tmplAttr["hx-swap"] = h.HxSwap
	}
	if h.HxPushUrl != nil {
		tmplAttr["hx-push-url"] = h.HxPushUrl
	}
	return tmplAttr
}

func Button(opts ButtonOptions) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<button")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, opts.TemplAttributes())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(opts.Text)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/components/inputs/button.templ`, Line: 63, Col: 13}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</button>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
