// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package inputs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type NumberFieldOptions struct {
	Id       *string
	Name     *string
	Value    *string
	Step     *string
	Varient  string
	Required bool
	Disabled bool
	ErrorMsg *string
}

func (b *NumberFieldOptions) TemplAttributes() templ.Attributes {
	tmplAttr := templ.Attributes{}

	if b.Id != nil {
		tmplAttr["id"] = b.Id
	}
	if b.Name != nil {
		tmplAttr["name"] = b.Name
	}
	if b.Value != nil {
		tmplAttr["value"] = b.Value
	}
	if b.Step != nil {
		tmplAttr["step"] = b.Step
	}
	btnClasses := " w-full p-2.5 focus:outline-none text-sm border-2 "
	if b.ErrorMsg != nil {
		switch b.Varient {
		case "outlined":
			focusTailwind := " focus:ring-varient-error-focus focus:border-varient-error-focus"
			tmplAttr["class"] = "rounded-lg border-varient-error block" + focusTailwind + btnClasses
		case "filled":
			focusTailwind := " focus:border-b-varient-error-focus"
			tmplAttr["class"] = "bg-bg-secondary border-b-varient-error border-t-transparent border-x-transparent block rounded-t-md" + focusTailwind + btnClasses
		case "standard":
			focusTailwind := " focus:border-b-varient-error-focus"
			tmplAttr["class"] = "border-b-varient-error border-t-transparent border-x-transparent block rounded-t-md" + focusTailwind + btnClasses
		default:
			focusTailwind := " focus:ring-varient-error-focus focus:border-varient-error-focus"
			tmplAttr["class"] = "rounded-lg border-varient-error block" + focusTailwind + btnClasses
		}
	} else {
		switch b.Varient {
		case "outlined":
			focusTailwind := " focus:ring-varient-primary focus:border-varient-primary"
			tmplAttr["class"] = "rounded-lg border-gray-300 block" + focusTailwind + btnClasses
		case "filled":
			focusTailwind := " focus:border-b-varient-primary"
			tmplAttr["class"] = "bg-bg-secondary border-b-txt-primary border-t-transparent border-x-transparent block rounded-t-md" + focusTailwind + btnClasses
		case "standard":
			focusTailwind := " focus:border-b-varient-primary"
			tmplAttr["class"] = "border-b-txt-primary border-t-transparent border-x-transparent block rounded-t-md" + focusTailwind + btnClasses
		default:
			focusTailwind := " focus:ring-varient-primary focus:border-varient-primary"
			tmplAttr["class"] = "rounded-lg border-gray-300 block" + focusTailwind + btnClasses
		}
	}

	if b.Required {
		tmplAttr["required"] = b.Required
	}
	if b.Disabled {
		tmplAttr["disabled"] = b.Disabled
	}

	return tmplAttr
}

func NumberField(opts NumberFieldOptions) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<input type=\"number\" autocomplete=\"off\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, opts.TemplAttributes())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("> ")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if opts.ErrorMsg != nil {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"text-varient-error text-xs pl-2\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var2 string
			templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(*opts.ErrorMsg)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `app/components/inputs/numberField.templ`, Line: 79, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</div>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
