// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package inputs

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

type TextFieldOptions struct {
	Id       *string
	Name     *string
	Value    *string
	Varient  string
	Required bool
	Disabled bool
}

func (b *TextFieldOptions) TemplAttributes() templ.Attributes {
	tmplAttr := templ.Attributes{}

	if b.Id != nil {
		tmplAttr["id"] = b.Id
	}
	if b.Name != nil {
		tmplAttr["name"] = b.Name
	}
	if b.Value != nil {
		tmplAttr["value"] = b.Value
	}
	btnClasses := " w-full p-2.5 focus:outline-none"
	switch b.Varient {
	case "outlined":
		tmplAttr["class"] = "rounded-lg border border-gray-300 text-sm focus:ring-varient-primary focus:border-varient-primary block" + btnClasses
	case "filled":
		tmplAttr["class"] = "bg-bg-secondary text-sm border border-b-txt-primary border-t-transparent border-x-transparent focus:border-b-varient-primary block rounded-t-md" + btnClasses
	case "standard":
		tmplAttr["class"] = "text-sm border border-b-txt-primary border-t-transparent border-x-transparent focus:border-b-varient-primary block rounded-t-md" + btnClasses
	default:
		tmplAttr["class"] = "rounded-lg border border-gray-300 text-sm focus:ring-varient-primary focus:border-varient-primary block" + btnClasses
	}

	if b.Required {
		tmplAttr["required"] = b.Required
	}
	if b.Disabled {
		tmplAttr["disabled"] = b.Disabled
	}

	return tmplAttr
}

func TextField(opts TextFieldOptions) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<input type=\"text\" autocomplete=\"off\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, opts.TemplAttributes())
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
